### ISSUE TITLE
Profile photos not circular

### ISSUE THREAD

**Issue by netbek** [ShuttleworthFoundation/shuttleworthfoundation.org#1]
Photos of the team and fellows are slightly deformed. I assume the images are meant to be circular. Here's a screenshot of how it looks in Firefox 35 and Chrome 40: ![www_shuttleworthfoundation_org_team_jason-hudson](https://cloud.githubusercontent.com/assets/1008866/6559698/4df63f7e-c68d-11e4-955a-3e7ed53f8c54.png)

Around https://github.com/ShuttleworthFoundation/shuttleworthfoundation.org/blob/master/css/custom.css#L395 in the `.photo` selector,  `max-width` and `max-height` should be equal:

```css
.photo {
  max-height: 220px;
  max-width: 220px;
}
```

**Comment by jasonhudson** [comment]
Thanks. All sorted.
