### ISSUE TITLE
Application form: ask about wider implications of proposal (building blocks)

### ISSUE THREAD

**Issue by tbm** [ShuttleworthFoundation/shuttleworthfoundation.org#24]
In addition to creating social change directly through the fellowship, the Foundation seems to encourage creating building blocks that other people can use to create further social change.

I wonder if it makes sense to add a question about this to the application form to see whether applicants have considered the wider context.

Of course, the downside of adding another question (even if it would be limited by, say, 750 characters) is that the application is quite long already.

(Feel free to close this issue if this was considered before or is not considered a good idea. It was just an idea I had.)

**Comment by jasonhudson** [comment]
Thank you for the suggestion. A lot of that is covered in the conversation we have with shortlisted applicants. We want to keep the form short and useful and cover other aspects of the proposal via a more high bandwidth face-to-face video call as part of the process.
