### ISSUE TITLE
No September 2020 intake?

### ISSUE THREAD

**Issue by tbm** [ShuttleworthFoundation/shuttleworthfoundation.org#42]
The September 2020 intake process would have started earlier this month but:

```
  next: March 2021
```

Would it make sense to write a blog mentioning there's no September intake?

This was done previously:
https://www.shuttleworthfoundation.org/thinking/2018/10/26/thinking-next-application-round/

**Comment by jasonhudson** [comment]
We're moving to one round per year with a March intake.

We operate a small fellowship programme with a single source of funding that is capped at $5 million per year. From time to time we need to make adjustments to the programme that keep costs in-check, but also ensure we don't dilute the value of the fellowship. Moving to one round per year is a mix of both these elements, ensuring that we are able to spend enough time on finding the right people for our fellowship and rationalising resources so they can be spent directly on programme costs.

I'll see if I can get a post up about it.

**Comment by tbm** [comment]
> I'll see if I can get a post up about it.

Thanks!

**Comment by jasonhudson** [comment]
[89fb6fe](https://github.com/ShuttleworthFoundation/shuttleworthfoundation.org/commit/89fb6fe1a3a81f76f4f83b66840d4c611a874209) --> One application round per year blog post
