### ISSUE TITLE
Mention "Fifty Shades of Green"

### ISSUE THREAD

**Issue by tbm** [ShuttleworthFoundation/shuttleworthfoundation.org#44]
I discovered "Fifty Shades of Green" on [GitHub](https://github.com/ShuttleworthFoundation/shuttleworth-foundation-shades-of-green/). I'm quite surprised that there was no blog when this was published and no link to the web site.

The book contains a ton of material not covered on the Foundation web site and gives a much better understanding of how you operate and what you're trying to achieve. I think everyone applying for a fellowship should read this book, so it would be great if this could be fixed.

**Comment by jasonhudson** [comment]
We've been meaning to do it for ages, but it just kept falling down the todo list. You can find it here: https://shuttleworthfoundation.org/book/

I'll get a post up asap.

**Comment by jasonhudson** [comment]
[f3bf721](https://github.com/ShuttleworthFoundation/shuttleworthfoundation.org/commit/f3bf721a8cf140cd88c9d26aa6122c0709ccbf97) --> Fifty Shades of Green book - blog post, cover image and link

**Comment by tbm** [comment]
Thanks @jasonhudson
